# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a45d8258f8a107836cb26d161093955531a246ad70439de5cecc4ad5757923c04b0de36487922c00fc02ff04c73884912ac750955d09f54358901909b11e435

test:
  secret_key_base: c366a1d33658afe7737207006f8d1d0cc79c7b488afb2e97efb08bd4ebf3fce09dbbdb27099f69a5c83ead1180254b6e1578eb2864b332c69bc3ed3f7b4dc35a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
